# Generated by Django 6.0.6 on 2026-06-11 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='role',
        ),
        migrations.AddField(
            model_name='answer',
            name='role_points_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='navigator.role', verbose_name='Додає бал до ролі'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок запитання'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст відповіді'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст запитання'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(verbose_name='Опис професії'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва ролі'),
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='Номер кроку')),
                ('title', models.CharField(max_length=150, verbose_name='Назва кроку')),
                ('description', models.TextField(verbose_name='Детальний опис кроку')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_steps', to='navigator.role')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва технології')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='navigator.role')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва вакансії')),
                ('link', models.URLField(verbose_name='Посилання на вакансію')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='navigator.role')),
            ],
        ),
    ]
